global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']
        
  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']