#!/bin/bash

# Superset Database Connection Helper
# Provides the exact connection details for easy copy-paste

echo "🔗 Superset Database Connection Details"
echo "========================================"
echo ""
echo "🏢 Main SaaS Platform Database (Read-Only Access)"
echo "   Database Name: SaaS Platform" 
echo "   SQLAlchemy URI: postgresql://superset_readonly:superset_readonly_password_2024@postgres:5432/saas_platform_dev"
echo ""
echo "📋 Copy this URI and paste it into Superset:"
echo "postgresql://superset_readonly:superset_readonly_password_2024@postgres:5432/saas_platform_dev"
echo ""
echo "🎯 Setup Steps:"
echo "   1. Go to http://localhost:8088"
echo "   2. Login: admin / admin_password_2024"
echo "   3. Settings → Database Connections → '+'"
echo "   4. Paste the URI above"
echo "   5. Test Connection → Save"
echo ""
echo "📊 Key Tables to Explore:"
echo "   • entity_customers     - Customer health and revenue metrics"
echo "   • entity_subscriptions - MRR, ARR, and subscription lifecycle"
echo "   • entity_devices       - IoT device performance and monitoring"
echo "   • entity_users         - User engagement and feature adoption"
echo "   • entity_campaigns     - Marketing attribution and ROI"
echo "   • entity_locations     - Multi-location operational metrics"
echo "   • entity_features      - Product feature adoption tracking"
echo ""
echo "💡 Pro Tips:"
echo "   • Use entity_*_daily/monthly tables for trend analysis"
echo "   • Use entity_*_history tables for temporal analytics"
echo "   • Use atomic entity_* tables for current-state dashboards"
echo ""
echo "🚀 Happy analyzing!"
