apiVersion: 1

datasources:
  - name: SaaS Platform PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: saas_platform_dev
    user: saas_user
    secureJsonData:
      password: saas_secure_password_2024
    jsonData:
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1300
      timescaledb: false
    isDefault: true
    editable: true
