name: Generate Documentation

on:
  # Run on pushes to main that modify schema or models
  push:
    branches: [main]
    paths:
      - 'database/schema/**'
      - 'transform/models/**'
      - 'scripts/documentation/**'
  
  # Run daily at 2 AM UTC
  schedule:
    - cron: '0 2 * * *'
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: saas_user
          POSTGRES_PASSWORD: saas_secure_password_2024
          POSTGRES_DB: saas_platform_dev
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Initialize database
      run: |
        # Create schemas
        PGPASSWORD=saas_secure_password_2024 psql -h localhost -U saas_user -d saas_platform_dev -f database/schema/00_create_schemas.sql
        
        # Create tables
        PGPASSWORD=saas_secure_password_2024 psql -h localhost -U saas_user -d saas_platform_dev -f database/schema/01_create_raw_tables.sql
        
        # Load sample data for documentation
        python scripts/generate_accounts.py
        python scripts/generate_locations.py
        python scripts/generate_devices.py
        python scripts/generate_users.py
        python scripts/generate_subscriptions.py
    
    - name: Run dbt models
      run: |
        cd transform
        dbt deps
        dbt seed
        dbt run
        cd ..
    
    - name: Generate documentation
      run: |
        python scripts/documentation/generate_all_docs.py
    
    - name: Commit documentation updates
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/
        git add edu/
        git diff --staged --quiet || git commit -m "🤖 Update documentation [skip ci]"
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main